// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ConsoleController from "./console_controller"
application.register("console", ConsoleController)

import ManageSelectionsController from "./manage_selections_controller"
application.register("manage-selections", ManageSelectionsController)

import PaginationController from "./pagination_controller"
application.register("pagination", PaginationController)

import PlexController from "./plex_controller"
application.register("plex", PlexController)

import SubmitOnKeyupController from "./submit_on_keyup_controller"
application.register("submit-on-keyup", SubmitOnKeyupController)
