
Style/Documentation:
  Enabled: false

Style/MixinUsage:
  Exclude:
    - 'Rakefile'

AllCops:
  TargetRubyVersion: 2.7.0
  Exclude:
    - bin/*
    - config/application.rb
    - config/unicorn.rb
    - Dangerfile
    - db/**/*
    - node_modules/**/*
    - vendor/**/*
