inherit_from: .rubocop_todo.yml

# Offense count: 25
Style/Documentation:
  Enabled: false

# Offense count: 45
# Configuration parameters: AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, IgnoredPatterns.
# URISchemes: http, https
Metrics/LineLength:
  Max: 100

Metrics/AbcSize:
  Max: 21

Metrics/BlockLength:
  Max: 32

Metrics/MethodLength:
  Max: 38

Metrics/PerceivedComplexity:
  Max: 10
