inherit_from: .rubocop_todo.yml

require: rubocop-rspec

Style/Documentation:
  Enabled: false

Style/MixinUsage:
  Exclude:
    - 'Rakefile'

AllCops:
  TargetRubyVersion: 2.7.0
  NewCops: enable
  Exclude:
    - bin/*
    - config/application.rb
    - config/unicorn.rb
    - Dangerfile
    - db/**/*
    - node_modules/**/*
    - vendor/**/*

Metrics/BlockLength:
  Exclude:
    - config/routes.rb  # Rails
    - lib/tasks/**/*    # Rake
    - spec/**/*         # RSpec
