inherit_from: .rubocop_todo.yml

require:
  - rubocop-rspec
  - rubocop-rails

Style/Documentation:
  Enabled: false

Style/MixinUsage:
  Exclude:
    - "Rakefile"

AllCops:
  TargetRubyVersion: 3.3.0
  NewCops: enable
  UseCache: true
  Exclude:
    - bin/*
    - config/application.rb
    - config/unicorn.rb
    - Dangerfile
    - db/**/*
    - node_modules/**/*
    - vendor/**/*

Metrics/BlockLength:
  Exclude:
    - config/routes.rb # Rails
    - lib/tasks/**/* # Rake
    - spec/**/* # RSpec

RSpec/MultipleMemoizedHelpers:
  Max: 6
