# frozen_string_literal: true

source 'https://rubygems.org'

gem 'actioncable'
gem 'activerecord'
gem 'dry-initializer'
gem 'dry-types'
gem 'httparty'
gem 'net-scp'
gem 'nokogiri'
gem 'rack'
gem 'rack-app', require: 'rack/app'
gem 'rake'
gem 'ruby-progressbar'
gem 'slack-notifier'
gem 'sqlite'
gem 'tty-prompt'
gem 'webpacker'
gem 'yarn'
gem 'zeitwerk'

group :development do
  gem 'capybara'
  gem 'capybara-screenshot'
  gem 'cucumber'
  gem 'faker'
  gem 'pry'
  gem 'rspec'
  gem 'rubocop'
  gem 'selenium-webdriver'
  gem 'solargraph'
  gem 'vcr'
  gem 'webmock'
end
